openapi: 3.0.1
info:
  title: Tour Operator API
  version: 1.0.0
  description: API for authentication, pricing data, and CSV uploads for tour operators.

servers:
  - url: https://localhost:5001/api

paths:
  /data/{tourOperatorId}:
    get:
      summary: Get pricing data
      description: Returns cached or fresh pricing data for the specified tour operator.
      parameters:
        - name: tourOperatorId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            default: 50
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Pricing data retrieved successfully
        "401":
          description: Unauthorized or blacklisted token
        "403":
          description: Forbidden
        "500":
          description: Internal server error

  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: Registration successful
        "409":
          description: Conflict (duplicate email or invalid operation)

  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful, returns JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Unauthorized

  /auth/logout:
    post:
      summary: Logout a user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logged out successfully

  /touroperators/{tourOperatorId}/pricing-upload:
    post:
      summary: Upload CSV pricing data
      description: Allows a TourOperator to upload pricing data in CSV format.
      parameters:
        - name: tourOperatorId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                connectionId:
                  type: string
      security:
        - bearerAuth: []
      responses:
        "202":
          description: Upload accepted and processing started
        "400":
          description: Invalid request (missing file)
        "403":
          description: Forbidden (tour operator mismatch)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        role:
          type: string
          enum: [Admin, TourOperator]
        tourOperatorId:
          type: string
          format: uuid
      required: [email, password, role]

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required: [email, password]

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        expiresAt:
          type: string
          format: date-time
